/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: runtime_debugger_log.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "runtime_debugger_log.pb-c.h"
void   runtime_debugger__log_node__init
                     (RuntimeDebugger__LogNode         *message)
{
  static const RuntimeDebugger__LogNode init_value = RUNTIME_DEBUGGER__LOG_NODE__INIT;
  *message = init_value;
}
size_t runtime_debugger__log_node__get_packed_size
                     (const RuntimeDebugger__LogNode *message)
{
  assert(message->base.descriptor == &runtime_debugger__log_node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t runtime_debugger__log_node__pack
                     (const RuntimeDebugger__LogNode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &runtime_debugger__log_node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t runtime_debugger__log_node__pack_to_buffer
                     (const RuntimeDebugger__LogNode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &runtime_debugger__log_node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RuntimeDebugger__LogNode *
       runtime_debugger__log_node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RuntimeDebugger__LogNode *)
     protobuf_c_message_unpack (&runtime_debugger__log_node__descriptor,
                                allocator, len, data);
}
void   runtime_debugger__log_node__free_unpacked
                     (RuntimeDebugger__LogNode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &runtime_debugger__log_node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   runtime_debugger__log_list__init
                     (RuntimeDebugger__LogList         *message)
{
  static const RuntimeDebugger__LogList init_value = RUNTIME_DEBUGGER__LOG_LIST__INIT;
  *message = init_value;
}
size_t runtime_debugger__log_list__get_packed_size
                     (const RuntimeDebugger__LogList *message)
{
  assert(message->base.descriptor == &runtime_debugger__log_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t runtime_debugger__log_list__pack
                     (const RuntimeDebugger__LogList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &runtime_debugger__log_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t runtime_debugger__log_list__pack_to_buffer
                     (const RuntimeDebugger__LogList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &runtime_debugger__log_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RuntimeDebugger__LogList *
       runtime_debugger__log_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RuntimeDebugger__LogList *)
     protobuf_c_message_unpack (&runtime_debugger__log_list__descriptor,
                                allocator, len, data);
}
void   runtime_debugger__log_list__free_unpacked
                     (RuntimeDebugger__LogList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &runtime_debugger__log_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor runtime_debugger__log_node__field_descriptors[5] =
{
  {
    "log_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RuntimeDebugger__LogNode, log_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_frame_count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RuntimeDebugger__LogNode, has_log_frame_count),
    offsetof(RuntimeDebugger__LogNode, log_frame_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(RuntimeDebugger__LogNode, has_log_type),
    offsetof(RuntimeDebugger__LogNode, log_type),
    &runtime_debugger__log_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_message",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RuntimeDebugger__LogNode, log_message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_stack_track",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RuntimeDebugger__LogNode, log_stack_track),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned runtime_debugger__log_node__field_indices_by_name[] = {
  1,   /* field[1] = log_frame_count */
  3,   /* field[3] = log_message */
  4,   /* field[4] = log_stack_track */
  0,   /* field[0] = log_time */
  2,   /* field[2] = log_type */
};
static const ProtobufCIntRange runtime_debugger__log_node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor runtime_debugger__log_node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RuntimeDebugger.LogNode",
  "LogNode",
  "RuntimeDebugger__LogNode",
  "RuntimeDebugger",
  sizeof(RuntimeDebugger__LogNode),
  5,
  runtime_debugger__log_node__field_descriptors,
  runtime_debugger__log_node__field_indices_by_name,
  1,  runtime_debugger__log_node__number_ranges,
  (ProtobufCMessageInit) runtime_debugger__log_node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor runtime_debugger__log_list__field_descriptors[1] =
{
  {
    "log_node_list",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RuntimeDebugger__LogList, n_log_node_list),
    offsetof(RuntimeDebugger__LogList, log_node_list),
    &runtime_debugger__log_node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned runtime_debugger__log_list__field_indices_by_name[] = {
  0,   /* field[0] = log_node_list */
};
static const ProtobufCIntRange runtime_debugger__log_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor runtime_debugger__log_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RuntimeDebugger.LogList",
  "LogList",
  "RuntimeDebugger__LogList",
  "RuntimeDebugger",
  sizeof(RuntimeDebugger__LogList),
  1,
  runtime_debugger__log_list__field_descriptors,
  runtime_debugger__log_list__field_indices_by_name,
  1,  runtime_debugger__log_list__number_ranges,
  (ProtobufCMessageInit) runtime_debugger__log_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue runtime_debugger__log_type__enum_values_by_number[5] =
{
  { "Error", "RUNTIME_DEBUGGER__LOG_TYPE__Error", 0 },
  { "Assert", "RUNTIME_DEBUGGER__LOG_TYPE__Assert", 1 },
  { "Warning", "RUNTIME_DEBUGGER__LOG_TYPE__Warning", 2 },
  { "Log", "RUNTIME_DEBUGGER__LOG_TYPE__Log", 3 },
  { "Exception", "RUNTIME_DEBUGGER__LOG_TYPE__Exception", 4 },
};
static const ProtobufCIntRange runtime_debugger__log_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex runtime_debugger__log_type__enum_values_by_name[5] =
{
  { "Assert", 1 },
  { "Error", 0 },
  { "Exception", 4 },
  { "Log", 3 },
  { "Warning", 2 },
};
const ProtobufCEnumDescriptor runtime_debugger__log_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RuntimeDebugger.LogType",
  "LogType",
  "RuntimeDebugger__LogType",
  "RuntimeDebugger",
  5,
  runtime_debugger__log_type__enum_values_by_number,
  5,
  runtime_debugger__log_type__enum_values_by_name,
  1,
  runtime_debugger__log_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
