name: update_submodule

on:
  push:
    branches:
    - dev

jobs:
  build_submodule:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: check
      run: |
        ls -alh
        ls -alh Assets/
        # ping -n 6 gitee.com

    - name: push submodule
      run: |
        git config --global user.name "coding2233"
        git config --global user.email "coding2233@163.com"
        git clone https://gitee.com/coding2233/GameFramework.git gf
        cp -r -f Assets/GameFramework gf/
        cp -r -f Assets/RuntimeDebugger gf/
        cd gf
        git commit -m "update submodule at $(date "+%Y-%m-%d %T") - by github actions"
        git remote set-url origin https://coding2233:${{ secrets.GITEE_PUSH_TOKEN }}@gitee.com/coding2233/GameFramework.git
        git push