name: build_xhv

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - xhv/**

jobs:
  build_hv_linux:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: xmake setup
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: build xhv
      run: |
        xmake --version
        cd xhv
        xmake -v -y
        ls -lah build
  
  build_hv_android_v8:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: xmake setup
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: android ndk setup
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false

    - name: build xhv
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        echo $ANDROID_NDK_HOME
        xmake --version
        cd xhv
        xmake f -p android --ndk=$ANDROID_NDK_HOME -a arm64-v8a -y
        xrepo install -y libhv
        xmake -y -v -b xhv
        ls -lah build

  build_hv_window:
    runs-on: windows-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: xmake setup
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: build xhv
      run: |
        xmake --version
        cd xhv
        xmake -v -y
        dir build

  build_hv_mac:
    runs-on: macos-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: xmake setup
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: build xhv
      run: |
        xmake --version
        cd xhv
        xmake -v -y
        ls -lah build
  
  build_hv_ios_arm64:
    runs-on: macos-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    
    - name: xmake setup
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: build xhv
      run: |
        xmake --version
        cd xhv
        xmake f -p iphoneos -a arm64 -y
        xmake -v -y
        ls -lah build
